name: bella-keys-personal-assist

services:
  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
      - POSTGRES_USER=${EMS_PG_DB_USER}
      - POSTGRES_PASSWORD=${EMS_PG_DB_PASSWORD}
      - POSTGRES_DB=${EMS_PG_DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bella-keys-network

  expense-manager-service:
    build: ./services/expense-manager-service
    container_name: expense-manager-service
    ports:
      - "8000:8000"
    environment:
      # App configurations
      - HOST=${EMS_HOST}
      - PORT=${EMS_PORT}
      - DEBUG=${EMS_DEBUG}
      # Database configurations
      - STORAGE_TYPE=${EMS_STORAGE_TYPE}
      - DATABASE_URL=${EMS_DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - bella-keys-network

  keys-personal-assist-ui:
    build: ./keys-personal-assist-ui
    container_name: keys-personal-assist-ui
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=${PERSONAL_ASSIST_UI_HOST}
      - PORT=${PERSONAL_ASSIST_UI_PORT}
      - NEXT_PUBLIC_EMS_API_URL=${NEXT_PUBLIC_EMS_API_URL}
      - NEXT_PUBLIC_BELLA_CHAT_API_URL=${NEXT_PUBLIC_BELLA_CHAT_API_URL}
    networks:
      - bella-keys-network

networks:
  bella-keys-network:
    driver: bridge
