name: bella-keys-personal-assist

services:
  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
      - POSTGRES_USER=${EMS_PG_DB_USER}
      - POSTGRES_PASSWORD=${EMS_PG_DB_PASSWORD}
      - POSTGRES_DB=${EMS_PG_DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bella-keys-network

  expense-manager-service:
    build: ./services/expense-manager-service
    container_name: expense-manager-service
    ports:
      - "8000:8000"
    environment:
      # App configurations
      - HOST=${EMS_HOST}
      - PORT=${EMS_PORT}
      - DEBUG=${EMS_DEBUG}
      # Database configurations
      - STORAGE_TYPE=${EMS_STORAGE_TYPE}
      - DATABASE_URL=${EMS_DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - bella-keys-network

  bella-chat-service:
    build: ./services/bella-chat-service
    container_name: bella-chat-service
    ports:
      - "5000:5000"
    environment:
      # Bella Service Settings
      - HOST=${BCS_HOST}
      - PORT=${BCS_PORT}
      - DEBUG=${BCS_DEBUG}
      # AI Settings
      - SYNTHESIS_MODEL_PROVIDER=${SYNTHESIS_MODEL_PROVIDER}
      - SYNTHESIS_MODEL_NAME=${SYNTHESIS_MODEL_NAME}
      - EMBEDDING_MODEL_PROVIDER=${EMBEDDING_MODEL_PROVIDER}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - EMBEDDING_MODEL_DIMENSION=${EMBEDDING_MODEL_DIMENSION}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Ollama Settings
      - OLLAMA_URL=${OLLAMA_URL}
      # QDRANT Settings
      - QDRANT_URL=${QDRANT_URL}
      # Keys Personal Wiki Agent Settings
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
    depends_on:
      - qdrant
    networks:
      - bella-keys-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - ./services/.db/qdrant/storage:/qdrant/storage
    networks:
      - bella-keys-network

  keys-personal-assist-ui:
    build: ./keys-personal-assist-ui
    container_name: keys-personal-assist-ui
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=${PERSONAL_ASSIST_UI_HOST}
      - PORT=${PERSONAL_ASSIST_UI_PORT}
      - NEXT_PUBLIC_EMS_API_URL=${NEXT_PUBLIC_EMS_API_URL}
      - NEXT_PUBLIC_BELLA_CHAT_API_URL=${NEXT_PUBLIC_BELLA_CHAT_API_URL}
    depends_on:
      - expense-manager-service
      - bella-chat-service
    networks:
      - bella-keys-network

networks:
  bella-keys-network:
    driver: bridge
