name: expense-manager-service

services:
  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - expense-manager-network

  expense-manager-service:
    build: .
    container_name: expense-manager-service
    ports:
      - "8000:8000"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - expense-manager-network

networks:
  expense-manager-network:
    driver: bridge
