# Indentations
line-length = 120

# Includes
include = ["app/**/*.py"]

# Excludes
exclude = [
    "**/alembic/versions/**",
]

# Other Configs
show-fixes = true

# Lints

[lint]
select = [
    "E",    # pycodestyle Errors
    "W",    # pycodestyle Warnings
    "F",    # Pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "D",    # pydocstyle
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "PL",   # Pylint
    "SIM",  # flake8-simplify
    "TC",   # flake8-type-checking
]

[lint.pydocstyle]
convention = "google"   # Google Style Docstring. Can be "numpy", "pep257", or "google"

[lint.per-file-ignores]
"__init__.py" = ["F401"]    # Ignore "unused-import (F401)" in __init__.py files
"app/routers/v1/endpoints/*.py" = ["B008"]   # Ignore "function-call-in-default-argument (B008)" in endpoint files
