name: bella-chat-service

services:
  bella-chat-service:
    build: .
    container_name: bella-chat-service
    ports:
      - "5000:5000"
    environment:
      # Bella Service Settings
      - HOST=${HOST}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      # AI Settings
      - SYNTHESIS_MODEL_PROVIDER=${SYNTHESIS_MODEL_PROVIDER}
      - SYNTHESIS_MODEL_NAME=${SYNTHESIS_MODEL_NAME}
      - EMBEDDING_MODEL_PROVIDER=${EMBEDDING_MODEL_PROVIDER}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - EMBEDDING_MODEL_DIMENSION=${EMBEDDING_MODEL_DIMENSION}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Ollama Settings
      - OLLAMA_URL=${OLLAMA_URL}
      # QDRANT Settings
      - QDRANT_URL=${QDRANT_URL}
      # Keys Personal Wiki Agent Settings
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
      # Arize Settings
      - ARIZE_ENABLED=${ARIZE_ENABLED}
      - ARIZE_TRACES_URL=${ARIZE_TRACES_URL}
      - ARIZE_PROJECT_NAME=${ARIZE_PROJECT_NAME}
    depends_on:
      - qdrant
    networks:
      - bella-chat-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - ../.db/qdrant/storage:/qdrant/storage
    networks:
      - bella-chat-network

networks:
  bella-chat-network:
    driver: bridge
