name: bella-chat-service

services:
  bella-chat-service:
    build: .
    container_name: bella-chat-service
    ports:
      - "5000:5000"
    environment:
      # Bella Service Settings
      - HOST=${HOST}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
      # AI Settings
      - SYNTHESIS_MODEL_PROVIDER=${SYNTHESIS_MODEL_PROVIDER}
      - SYNTHESIS_MODEL_NAME=${SYNTHESIS_MODEL_NAME}
      - EMBEDDING_MODEL_PROVIDER=${EMBEDDING_MODEL_PROVIDER}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - EMBEDDING_MODEL_DIMENSION=${EMBEDDING_MODEL_DIMENSION}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Ollama Settings
      - OLLAMA_URL=${OLLAMA_URL}
      # QDRANT Settings
      - QDRANT_URL=${QDRANT_URL}
      # Keys Personal Wiki Agent Settings
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
      # Arize Settings
      - ARIZE_ENABLED=${ARIZE_ENABLED}
      - ARIZE_TRACES_URL=${ARIZE_TRACES_URL}
      - ARIZE_PROJECT_NAME=${ARIZE_PROJECT_NAME}
    depends_on:
      - qdrant
    networks:
      - bella-chat-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    volumes:
      - ../.db/qdrant/storage:/qdrant/storage
    networks:
      - bella-chat-network

  postgres:
    image: postgres:latest
    container_name: postgres-database
    environment:
      - POSTGRES_USER=${ARIZE_PG_DB_USER}
      - POSTGRES_PASSWORD=${ARIZE_PG_DB_PASSWORD}
      - POSTGRES_DB=${ARIZE_PG_DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bella-chat-network

  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: phoenix
    depends_on:
      - postgres
    ports:
      - 6006:6006 # PHOENIX_PORT
      - 4317:4317 # PHOENIX_GRPC_PORT
      - 9090:9090 # [Optional] PROMETHEUS PORT IF ENABLED
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://${ARIZE_PG_DB_USER}:${ARIZE_PG_DB_PASSWORD}@${ARIZE_PG_DB_HOST}:5432/${ARIZE_PG_DB_NAME}
    networks:
      - bella-chat-network

networks:
  bella-chat-network:
    driver: bridge
